### ISSUE TITLE
Episode 8: Monitoring Jupyterhub notebooks

### ISSUE THREAD

**Issue by goern** [operate-first/espresso-series#13]
Title
Monitoring Jupyterhub notebooks

User Story
As a data scientist, I want to know how I can monitor my jupyter hub notebooks running on Operate First cluster. If I run a machine learning workload in a local environment, I use tools like htop to monitor memory, cpu, and disk usage. If I work on the cluster, I want to know how I can monitor it so that I can debug my notebook.

Teaser
So we have all the tools to develop a data science notebook, but what happens when different personas work together on a single project? 

Release Date
TBD

[Script URL](https://docs.google.com/document/d/1VdysZ0ymZIZvwX4vVAZqfQtL4QGlzFGc-XNXnopXlio/edit?usp=sharing)

**Comment by tumido** [comment]
@Shreyanand  do you have anything in mind for this already? I've been also tasked to record a short video to demo the JH dashboard I've created. Maybe I can make it as a part of this espresso series. Wanna join forces on this one? :slightly_smiling_face:

**Comment by Shreyanand** [comment]
@tumido sure, I think that's a good idea! 
I've a rough flow outlined. So, the idea for this particular talk is that the data scientist (user of JH on OF) tries to monitor their workload and troubleshoots along the way. In season 1, all the videos are from the perspective of a data scientist. In season 2 we'd have DevOps perspective. This [doc](https://docs.google.com/document/d/1vvyn4UMX93wL9SM4q4xbxneGSrXSHCzhUCuKRSezzDo/edit#heading=h.rfne2tq9rrx0) shows the background work of the talks. 
Maybe you could talk about the Devops side of things for a video in season 2? Like creating the JH dashboard from Prometheus metrics, the blueprints directory and feature files for user issues, and other relevant admin side of things for the cluster? We could work on and record these two videos together since there are overlaps. What say?

**Comment by Shreyanand** [comment]
Rough structure:

1. Opening
2. Spawn a JH image with new account
3. Run a notebook with high disk requirement, see PVC error
4. Open Grafana dashboard
5. Open pod logs? (not everyone has access, Yet)
6. Create an issue on support repository
7. Open a notebook, run memory intensive matrix operation
8. Open Grafana dashboard, track memory, cpu, pvc
9. Show the state of kernel dying due to memory limitation
10. Spawn a new image with higher memory and run the same workload
11. Closing

**Comment by Shreyanand** [comment]
Hey there! @goern @tumido @MichaelClifford @oindrillac @isabelizimm @pacospace @durandom The rough outline for the talk is [here](https://docs.google.com/document/d/1VdysZ0ymZIZvwX4vVAZqfQtL4QGlzFGc-XNXnopXlio/edit?usp=sharing). Please let me know your comments so that it can be improved :)

**Comment by tumido** [comment]
@Shreyanand we now (finally) have merged a better "user perspective" dashboard for JH. It's the one I've created and demoed few weeks back on AIOps mtg. https://github.com/operate-first/apps/pull/697

It has logs from the pods + it also allows you to monitor your spark cluster if you deploy any.

Maybe this episode should rather focus on this new dashboard than the SRE oriented, wdyt?

Take a look:
![screencapture-grafana-route-opf-monitoring-apps-zero-massopen-cloud-d-fuJBFErMa-wip-jupyterhub-user-perspective-2021-06-03-13_08_21](https://user-images.githubusercontent.com/7453394/120636173-9aa64780-c46d-11eb-83f6-85c78f7853f4.png)

I'll link the live dashboard here, once it's up in the cluster. We've run into some issues with ODH operator recently so it may take few moments... :disappointed:

**Comment by MichaelClifford** [comment]
@Shreyanand outline looks good. Just added some minor comments

**Comment by Shreyanand** [comment]
> @Shreyanand outline looks good. Just added some minor comments

Thanks! Resolved the comments, I'll add the full script next.

**Comment by Shreyanand** [comment]
The script is ready for any kind of review.

**Comment by MichaelClifford** [comment]
@Shreyanand Script looks good. Just a couple of comments.

**Comment by isabelizimm** [comment]
Video [here](https://drive.google.com/file/d/1t520N_KPS9uxTRld4YXVmQHvZbS-KAFh/view?usp=sharing) for viewing!

CC: @durandom @MichaelClifford @Shreyanand @aakankshaduggal @goern @oindrillac @pacospace

**Comment by MichaelClifford** [comment]
@Shreyanand  @isabelizimm Not sure if its my speakers, but the audio sounds like its doubled, like two tracks playing a fraction of a second apart. Anyone else hearing this? Any way to fix it without re-recording?

**Comment by oindrillac** [comment]
+1 maybe lowering the reverb can help?

**Comment by isabelizimm** [comment]
I can try that! I had heard it initially in a few places, but thought I had fixed it :)

**Comment by isabelizimm** [comment]
Changed settings that I was able to--I can't hear an echo, but lmk if that is a universal experience or not. [video](https://drive.google.com/file/d/1ICgqXLGlZpYC-C0UxbXWoFlu3rwKZdqH/view?usp=sharing)

**Comment by Shreyanand** [comment]
@isabelizimm thanks it sounds better! Could we also switch the PVC exceeded screenshare clip that we discussed? It would make  more sense to the audience in that part.

**Comment by isabelizimm** [comment]
Updated! Next iteration of draft [here](https://drive.google.com/file/d/1iVc2VNY9daLyu9KRyKvXu8v1XKr29Onv/view?usp=sharing). LMK of any further changes necessary.

**Comment by isabelizimm** [comment]
Published on [YouTube](https://youtu.be/1zZ-7mdxOWU).
