### ISSUE TITLE
Episode 9: How to PR review in Data Science

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/espresso-series#21]

**Comment by MichaelClifford** [comment]
@aakankshaduggal Do you have a draft you want to share for this video?

**Comment by aakankshaduggal** [comment]
Hello Team,
Here is a [rough presentation](https://docs.google.com/presentation/d/1aJ-1irbIWVXCfAfDN4fZJD-KKLOn-Wyj8l8vTNIjFxs/edit?usp=sharing) of the content I am planning to share in the video for "[10 Principles of Data Science Code Review](https://www.operate-first.cloud/data-science/data-science-workflows/docs/guidelines-for-reviewing-datascience-code.md)"

@MichaelClifford @pacospace @isabelizimm @goern @durandom @Shreyanand @oindrillac Please review the document for the overall flow and high-level overview. The comments for each slide reside in the speaker notes. 

Once this issue is signed off, I will start working on the final script.

**Comment by isabelizimm** [comment]
lgtm!

**Comment by aakankshaduggal** [comment]
I have added to the [slides](https://docs.google.com/presentation/d/1aJ-1irbIWVXCfAfDN4fZJD-KKLOn-Wyj8l8vTNIjFxs/edit?usp=sharing) and it is up for review again! 
@isabelizimm @MichaelClifford @oindrillac @pacospace @Shreyanand @durandom @goern

**Comment by MichaelClifford** [comment]
:clap: :clap: :clap: 
/lgtm

**Comment by isabelizimm** [comment]
love the LGTM cat on slide 3 :laughing:
/lgtm

**Comment by isabelizimm** [comment]
Draft of video [here](https://drive.google.com/file/d/1p4F1vJK8YDMa0Xo1MGNYXLqdWucYJeY3/view?usp=sharing). Reviews?

**Comment by aakankshaduggal** [comment]
Thank you so much @isabelizimm for putting this together :smile: 
Please let us know how this looks to you all. 
cc- @MichaelClifford, @oindrillac , @pacospace, @Shreyanand, @durandom , @goern

**Comment by MichaelClifford** [comment]
:clap: :clap:
/lgtm

**Comment by isabelizimm** [comment]
Published on [YouTube](https://youtu.be/Wfu_3UVQoKA). Feel free to reopen issue if we need to make further updates.
